version: '3.8'

services:
  grafana:
    image: grafana/grafana-oss:9.4.3
    container_name: grafana
    restart: unless-stopped
    depends_on:
      - jaeger
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - '13000:3000'

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14269:14269
      - 14250:14250
      - 9411:9411
      - 4317:4317
      - 4318:4318

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - jaeger
    ports:
      - '19090:9090'

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ngixn-proxy
    restart: unless-stopped
    depends_on:
      - jaeger
    ports:
      - 8080:80
volumes:
  grafana-data: {}
